---
- name: Using length 
  hosts: web
  tasks:
  - name: Using the length
    ansible.builtin.debug:
      msg: "{{ my_var | default('ansible_automation') }}"
    register: result
  - name: Print the result 
    ansible.builtin.debug:
      var: result
  - name: Print the custom message
    ansible.builtin.debug:
      msg: "The value of the variable is '{{ result.msg }}' and length of the variable is '{{ result.msg | length }}'" 
...
