download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/myns-mycollection-1.0.1.tar.gz
format_version: 1.0.0
name: mycollection
namespace: myns
server: https://hub.lab.example.com/api/galaxy/content/published/
signatures: []
version: 1.0.1
version_url: /api/galaxy/content/published/v3/plugin/ansible/content/published/collections/index/myns/mycollection/versions/1.0.1/
