---
- name: Create a user and install a package
  hosts: dbserver
  vars:
    my_user: dell
  vars_files:
  - secret.yml
  tasks:
  - name: Create the {{ my_user }} user
    ansible.builtin.user:
      name: "{{ my_user }}"
      password: "{{ password }}"
      state: present
...
