---
- name: Using SELINUX roles
  hosts: apache
  become: true
  tasks:
  - block:
    - name: enable selinux
      include_role:
        name: redhat.rhel_system_roles.selinux
    rescue:
    - name: Reboot the system
      ansible.builtin.reboot:

    - name: Labeling the system
      include_role:
        name: redhat.rhel_system_roles.selinux
...

