download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/azure-azcollection-3.0.0.tar.gz
format_version: 1.0.0
name: azcollection
namespace: azure
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/azure/azcollection/versions/3.0.0/
