---
- name: List used in an improper way
  hosts: web
  become: true
  tasks:
  - name: Install package
    ansible.builtin.yum: 
      name: "{{ item }}"
      state: latest
    loop:
    - httpd
    - firewalld
...
