---
- name: Using variables
  hosts: webserver
  become: true
  vars_files:
  - variable.yml
  tasks:
  - name: Install the {{ package }} package
    ansible.builtin.dnf:
      name: "{{ package }}"
      state: latest
...
